name: pysolace package

on: [push]

jobs: 
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        include:
          - python-version: 3.6
            pysolace-whl: pysolace-0.0.1-cp36-cp36m-macosx_10_14_x86_64.whl
          - python-version: 3.7
            pysolace-whl: pysolace-0.0.1-cp37-cp37m-macosx_10_14_x86_64.whl
          - python-version: 3.8
            pysolace-whl: pysolace-0.0.1-cp38-cp38-macosx_10_14_x86_64.whl
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install pysolace
        run: pip install  ${{ matrix.pysolace-whl }}
      - name: test
        run: python test.py
      - name: set release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - name: test env version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}